In [1]:
import pandas as pd 
import numpy as np  

In [22]:
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression 

In [23]:
my_data=pd.read_csv("Admission_Predict.csv")

In [24]:
my_data

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

    Research  Chance of Admit   
0        Yes              0.92  
1        Yes              0.76  
2        Yes              0.72  
3        Yes              0.80  
4         No              0.65  
..       ...               ...  
395      Yes              0.82  
396      Yes              0.84  
397      Yes              0.91  
398       No              0.67  
399      Yes              0.95  

[400 rows x 9 columns]

In [25]:
x=my_data.iloc[:,1:6].values
y=my_data.iloc[:,8].values

In [26]:
x

array([[337. , 118. ,   4. ,   4.5,   4.5],
       [324. , 107. ,   4. ,   4. ,   4.5],
       [316. , 104. ,   3. ,   3. ,   3.5],
       ...,
       [330. , 116. ,   4. ,   5. ,   4.5],
       [312. , 103. ,   3. ,   3.5,   4. ],
       [333. , 117. ,   4. ,   5. ,   4. ]])

In [27]:
y

array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
       0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
       0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
       0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
       0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
       0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
       0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
       0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
       0.64, 0.74, 0.64, 0.38, 0.34, 0.44, 0.36, 0.42, 0.48, 0.86, 0.9 ,
       0.79, 0.71, 0.64, 0.62, 0.57, 0.74, 0.69, 0.87, 0.91, 0.93, 0.68,
       0.61, 0.69, 0.62, 0.72, 0.59, 0.66, 0.56, 0.45, 0.47, 0.71, 0.94,
       0.94, 0.57, 0.61, 0.57, 0.64, 0.85, 0.78, 0.84, 0.92, 0.96, 0.77,
       0.71, 0.79, 0.89, 0.82, 0.76, 0.71, 0.8 , 0.78, 0.84, 0.9 , 0.92,
       0.97, 0.8 , 0.81, 0.75, 0.83, 0.96, 0.79, 0.

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [29]:
lm=LinearRegression()

In [30]:
lm.fit(x_train,y_train)

LinearRegression()

In [31]:
Ypredict=lm.predict(x_test)

In [32]:
Ypredict

array([0.70495406, 0.69291556, 0.78568707, 0.6061276 , 0.7072867 ,
       0.61266304, 0.69047488, 0.70123163, 0.84580681, 0.91939541,
       0.5355264 , 0.88723487, 0.74162195, 0.51781579, 0.85874756,
       0.60496869, 0.60353639, 0.76946379, 0.63949446, 0.74132672,
       0.90220947, 0.8782899 , 0.63308567, 0.48060521, 0.77983364,
       0.58969337, 0.48580374, 0.66387244, 0.93032265, 0.69042713,
       0.6487936 , 0.75485794, 0.73610957, 0.5224955 , 0.80669824,
       0.7818399 , 0.72816583, 0.838756  , 0.62862955, 0.89615978,
       0.74981328, 0.70783332, 0.77099694, 0.81241033, 0.8446517 ,
       0.76371325, 0.64793911, 0.74234633, 0.60776892, 0.60320463,
       0.65944411, 0.77371828, 0.61629201, 0.93076649, 0.68931393,
       0.72455886, 0.85726216, 0.77727561, 0.79505189, 0.81963889,
       0.75510933, 0.43717637, 0.64999109, 0.53986851, 0.85621329,
       0.75803769, 0.71501617, 0.8492394 , 0.77342843, 0.7222336 ,
       0.64797025, 0.81683865, 0.75765817, 0.64489129, 0.93355

In [37]:
comparison=pd.DataFrame(x_test,columns=['GRE Score','TOEFL Score','University Rating','SOP','LOR '])

In [38]:
comparison["AVL_o/p"]=y_test

In [39]:
comparison["pred_o/p"]=Ypredict

In [40]:
comparison

GRE Score  TOEFL Score  University Rating  SOP  LOR   AVL_o/p  pred_o/p
0       309.0        105.0                5.0  3.5   3.5     0.71  0.704954
1       308.0        110.0                4.0  3.5   3.0     0.70  0.692916
2       326.0        110.0                3.0  3.5   3.5     0.79  0.785687
3       306.0        105.0                2.0  3.0   2.5     0.73  0.606128
4       316.0        105.0                3.0  3.0   3.5     0.72  0.707287
..        ...          ...                ...  ...   ...      ...       ...
75      311.0        104.0                3.0  3.5   2.0     0.61  0.625947
76      306.0        103.0                2.0  2.5   3.0     0.69  0.611429
77      313.0        106.0                2.0  2.5   2.0     0.62  0.627317
78      334.0        116.0                4.0  4.0   3.5     0.93  0.874822
79      297.0         96.0                2.0  2.5   1.5     0.43  0.476725

[80 rows x 7 columns]