In [2]:
import numpy as np

In [3]:
arr=np.array(6)

In [4]:
arr

array(6)

In [5]:
arr1=np.array([1,2,3,4,5,6])

In [6]:
arr1

array([1, 2, 3, 4, 5, 6])

In [7]:
arr2=np.array([[1,2,3],[4,5,6]])

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

**array types**

**1.zero array**

**2.ones array**

**3.empty array**

**4.array for range**

In [9]:
zero_array=np.zeros((2,2))

In [10]:
zero_array

array([[0., 0.],
       [0., 0.]])

In [11]:
ones_array=np.ones((2,2))

In [12]:
ones_array

array([[1., 1.],
       [1., 1.]])

In [13]:
arr3=np.arange(6)

In [14]:
arr3

array([0, 1, 2, 3, 4, 5])

In [15]:
arr4=np.arange(2,20,4)

In [16]:
arr4

array([ 2,  6, 10, 14, 18])

In [17]:
arr5=np.transpose(arr2)

In [18]:
arr5

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
a1=np.array([2,2])
a2=np.array([4,5])

In [20]:
a1

array([2, 2])

In [21]:
a2

array([4, 5])

In [22]:
concat=np.concatenate((a1,a2))

In [23]:
concat

array([2, 2, 4, 5])

In [24]:
hori=np.hstack((a1,a2))

In [25]:
hori

array([2, 2, 4, 5])

In [26]:
ver=np.vstack((a1,a2))

In [27]:
ver

array([[2, 2],
       [4, 5]])

In [32]:
mat=np.array([[8,9,3],[1,2,2],[6,5,3]])

In [33]:
det_of_mat=np.linalg.det(mat)

In [34]:
det_of_mat

27.999999999999996

In [35]:
inverse=np.linalg.inv(mat)

In [36]:
inverse

array([[-0.14285714, -0.42857143,  0.42857143],
       [ 0.32142857,  0.21428571, -0.46428571],
       [-0.25      ,  0.5       ,  0.25      ]])

In [37]:
dense=np.array(([1,0,0,0],[1,2,0,0],[2,0,0,1],[2,0,0,0]))

In [38]:
dense

array([[1, 0, 0, 0],
       [1, 2, 0, 0],
       [2, 0, 0, 1],
       [2, 0, 0, 0]])

In [39]:
from scipy.sparse import csr_matrix

In [40]:
sparse=csr_matrix(dense)

In [42]:
sparse

<4x4 sparse matrix of type '<class 'numpy.int32'>'
	with 6 stored elements in Compressed Sparse Row format>

In [43]:
print(sparse)

  (0, 0)	1
  (1, 0)	1
  (1, 1)	2
  (2, 0)	2
  (2, 3)	1
  (3, 0)	2
