In [2]:
import numpy as np

In [23]:
arr=np.array(6)

In [24]:
arr

array(6)

In [15]:
arr1=np.array([1,2,3,4,5,6])

In [25]:
arr1

array([1, 2, 3, 4, 5, 6])

In [45]:
arr2=np.array([[1,2,3],[4,5,6]])

In [46]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

**array types**

**1.zero array**

**2.ones array**

**3.empty array**

**4.array for range**

In [47]:
zero_array=np.zeros((2,2))

In [48]:
zero_array

array([[0., 0.],
       [0., 0.]])

In [49]:
ones_array=np.ones((2,2))

In [50]:
ones_array

array([[1., 1.],
       [1., 1.]])

In [51]:
arr3=np.arange(6)

In [52]:
arr3

array([0, 1, 2, 3, 4, 5])

In [53]:
arr4=np.arange(2,20,4)

In [54]:
arr4

array([ 2,  6, 10, 14, 18])

In [55]:
arr5=np.transpose(arr2)

In [56]:
arr5

array([[1, 4],
       [2, 5],
       [3, 6]])

In [57]:
a1=np.array([2,2])
a2=np.array([4,5])

In [58]:
a1

array([2, 2])

In [59]:
a2

array([4, 5])

In [65]:
concat=np.concatenate((a1,a2))

In [66]:
concat

array([2, 2, 4, 5])

In [61]:
hori=np.hstack((a1,a2))

In [62]:
hori

array([2, 2, 4, 5])

In [63]:
ver=np.vstack((a1,a2))

In [64]:
ver

array([[2, 2],
       [4, 5]])